plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
}

group = 'com.br.unifor'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-validation:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-actuator:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-cache:3.4.5'

	implementation 'org.flywaydb:flyway-core:10.10.0'
	implementation 'org.flywaydb:flyway-database-postgresql:10.10.0'

	runtimeOnly 'org.postgresql:postgresql:42.7.3'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'

	compileOnly 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'

	developmentOnly 'org.springframework.boot:spring-boot-devtools:3.4.5'

	testImplementation 'org.springframework.boot:spring-boot-starter-test:3.4.5'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

tasks.named('test') {
	useJUnitPlatform()
}